/**************************************************************************
 *   Created: 2008/12/15 2:37
 *    Author: Eugene V. Palchukovsky
 *    E-mail: eugene@palchukovsky.com
 * -------------------------------------------------------------------
 *   Project: TunnelEx
 *       URL: http://tunnelex.net
 * -------------------------------------------------------------------
 *       $Id: Constants.h 1127 2011-02-22 17:23:32Z palchukovsky $
 **************************************************************************/

#ifndef INCLUDED_FILE__TUNNELEX__Constants_h__0812150237
#define INCLUDED_FILE__TUNNELEX__Constants_h__0812150237

#define _STR(a) #a
#define _XSTR(a) _STR(a)

#define _WSTR(a) L#a
#define _XWSTR(a) _WSTR(a)

#ifdef _DEBUG
#	define TUNNELEX_FILE_MODIFICATOR		"_dbg"
#else // #ifdef _DEBUG
#	ifdef TEST
#		define TUNNELEX_FILE_MODIFICATOR	"_test"
#	else // #ifdef TEST
#		define TUNNELEX_FILE_MODIFICATOR
#	endif
#endif // #ifdef _DEBUG

#define TUNNELEX_SOAP_SERVICE_PORT 2901

#define TUNNELEX_LICENSE_SERVICE_SUBDOMAIN		"licensing"
#define TUNNELEX_LICENSE_SERVICE_SUBDOMAIN_W	_XWSTR(TUNNELEX_LICENSE_SERVICE_SUBDOMAIN)

#define TUNNELEX_CORE_FILE_NAME					"TunnelEx"
#define TUNNELEX_SERVICE_FILE_NAME				"TunnelEx"
#define TUNNELEX_CONTROL_CENTER_FILE_NAME		"TunnelExControlCenter"
#define TUNNELEX_LEGACY_FILE_NAME				"TexLegacy"
#define TUNNELEX_MODULE_PIPE_FILE_NAME			"TexModPipe"
#define TUNNELEX_MODULE_INET_FILE_NAME			"TexModInet"
#define TUNNELEX_MODULE_SERIAL_FILE_NAME		"TexModSerial"
#define TUNNELEX_MODULE_PATHFINDER_FILE_NAME	"TexModPathfinder"
#define TUNNELEX_MODULE_UPNP_FILE_NAME			"TexModUpnp"

#define TUNNELEX_CORE_DLL_FILE_NAME					TUNNELEX_SERVICE_FILE_NAME TUNNELEX_FILE_MODIFICATOR ".dll"
#define TUNNELEX_SERVICE_EXE_FILE_NAME				TUNNELEX_SERVICE_FILE_NAME TUNNELEX_FILE_MODIFICATOR ".exe"
#define TUNNELEX_CONTROL_CENTER_EXE_FILE_NAME		TUNNELEX_CONTROL_CENTER_FILE_NAME TUNNELEX_FILE_MODIFICATOR ".exe"
#define TUNNELEX_LEGACY_DLL_FILE_NAME				TUNNELEX_LEGACY_FILE_NAME TUNNELEX_FILE_MODIFICATOR ".dll"
#define TUNNELEX_MODULE_PIPE_DLL_FILE_NAME			TUNNELEX_MODULE_PIPE_FILE_NAME TUNNELEX_FILE_MODIFICATOR ".dll"
#define TUNNELEX_MODULE_INET_DLL_FILE_NAME			TUNNELEX_MODULE_INET_FILE_NAME TUNNELEX_FILE_MODIFICATOR ".dll"
#define TUNNELEX_MODULE_INET_LIB_FILE_NAME			TUNNELEX_MODULE_INET_FILE_NAME TUNNELEX_FILE_MODIFICATOR ".lib"
#define TUNNELEX_MODULE_SERIAL_DLL_FILE_NAME		TUNNELEX_MODULE_SERIAL_FILE_NAME TUNNELEX_FILE_MODIFICATOR ".dll"
#define TUNNELEX_MODULE_SERIAL_LIB_FILE_NAME		TUNNELEX_MODULE_SERIAL_FILE_NAME TUNNELEX_FILE_MODIFICATOR ".lib"
#define TUNNELEX_MODULE_PATHFINDER_DLL_FILE_NAME	TUNNELEX_MODULE_PATHFINDER_FILE_NAME TUNNELEX_FILE_MODIFICATOR ".dll"
#define TUNNELEX_MODULE_PATHFINDER_LIB_FILE_NAME	TUNNELEX_MODULE_PATHFINDER_FILE_NAME TUNNELEX_FILE_MODIFICATOR ".lib"
#define TUNNELEX_MODULE_UPNP_DLL_FILE_NAME			TUNNELEX_MODULE_UPNP_FILE_NAME TUNNELEX_FILE_MODIFICATOR ".dll"
#define TUNNELEX_MODULE_UPNP_LIB_FILE_NAME			TUNNELEX_MODULE_UPNP_FILE_NAME TUNNELEX_FILE_MODIFICATOR ".lib"

#define TUNNELEX_MODULE_INET_NAME "Inet Module"
#define TUNNELEX_MODULE_INET_NAME_FULL TUNNELEX_NAME " " TUNNELEX_MODULE_INET_NAME

#endif // INCLUDED_FILE__TUNNELEX__Constants_h__0812150237
